### ISSUE TITLE
English code and comments

### ISSUE THREAD

**Issue by PotHix** [drbeco/xadreco#2]
What about to keep all variables and comments english only? It will help everyone in the world to understand the code better. :)

**Comment by drbeco** [comment]
Comments, yes, great idea! 

I was thinking in add doxygen, and generate documentation for all (english only). But keep portuguese comments as well, inside the code, as its used in Brazil a lot.

Variable, I'm not sure if we should change that. At least not for now.

**Comment by PotHix** [comment]
Cool, doxygen looks a good idea. :+1: 

About the code, are you using it for educational purposes? In negative case I keep my opinion on changing everything to english. Xadreco looks a good project and I think it will gain more popularity around the world with everything in English.

Just for the record, I'm brazilian and I think every developer should be comfortable with English, it is really necessary for the profession IHO. :)
